# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using pip command to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up . Install NumPy by going to your terminal or command prompt and typing:**
    
    pip install numpy
    


## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
for i in range(5):
    print(i)

0
1
2
3
4


## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
list(range(0,11,2))

[0, 2, 4, 6, 8, 10]

In [19]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(3)

array([1., 1., 1.])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

1. Start: The starting value of the sequence.
2. Stop: The ending value of the sequence.
3. Num: The number of evenly spaced values to generate between the  start and stop values, inclusive.

In [28]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [34]:
np.linspace(0,1,10) # Each element of the array is spaced 0.1 units apart from the previous one since (1 - 0) / 10 = 0.1.

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## eye

Creates an identity matrix

In [37]:
np.eye(4) # generates a 4x4 identity matrix. Here's what the matrix looks 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

uniform distribution between 0 (inclusive) and 1 (exclusive).

Inclusive - Including the last number

Exclusive - Excluding the last number

In [52]:
np.random.rand(2)   # generate an array of random numbers from a uniform distribution over the interval [0, 1)

array([0.07693407, 0.21576517])

In [56]:
np.random.rand(5,4)

array([[0.60151267, 0.81596098, 0.47316479, 0.62302239],
       [0.60489045, 0.68970521, 0.21277045, 0.74763349],
       [0.50600012, 0.14654854, 0.45831048, 0.01755196],
       [0.13156992, 0.10405298, 0.98437342, 0.92946254],
       [0.14683638, 0.2696323 , 0.96500658, 0.7105842 ]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

The np.random.randn() function is part of the NumPy library in Python and is used to generate an array of random numbers from a standard normal distribution (also known as Gaussian distribution) with a mean of 0 and a standard deviation of 1. 

In [53]:
np.random.randn(20)

array([-6.47649246e-02,  5.72426741e-01, -2.13814495e-01,  7.20209743e-01,
        1.23931777e+00,  1.32899627e+00, -9.63581461e-01, -6.64184874e-01,
       -2.34396444e-01, -2.19587227e-01,  2.54124201e+00, -3.07233919e-01,
        2.13461607e-01, -1.53534806e-01, -8.13346049e-01,  1.54220232e-03,
       -2.02700504e+00,  2.06165058e-01,  9.18015177e-01,  7.96965047e-02])

In [57]:
np.random.randn(5,5) # enerates a 2-dimensional array with 5 rows and 7 columns, containing random numbers sampled from a standard normal distribution. 

array([[ 0.48914489, -2.05852481,  1.16045157,  0.96634224, -0.06437262],
       [-0.27746074,  0.17030844,  0.39713962, -0.02681423,  0.44720287],
       [-0.20855633,  0.89687912, -0.18765635, -0.35184781, -0.59994525],
       [-0.42194629,  1.33417744, -0.75811162, -1.19682482,  0.1915525 ],
       [-0.59002517,  0.26162904, -0.4671194 ,  0.20738243,  1.12565648]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [72]:
np.random.randint(100)

75

In [74]:
np.random.randint(0,100,10) #generates an array of 10 random integers between 0 (inclusive) and 100 (exclusive)

array([72,  6, 10, 84, 54, 20, 59, 49, 25, 50])

In [75]:
np.random.randint(1000,size = (3,6)) 

#generates a 2-dimensional array with a shape of 3 rows and 6 columns, containing random integers between 0 (inclusive) and 1000 (exclusive)

array([[538,  42, 475, 945, 260, 943],
       [937, 863, 269, 821, 178, 905],
       [782, 798, 609, 497, 306,  64]])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [78]:
arr = np.arange(20)
#ranarr = np.random.randint(0,50,10)

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
ranarr

array([16, 49, 28,  9,  0,  7, 33, 20, 47,  7])

## Reshape
Returns an array containing the same data with a new shape.

In [25]:
arr.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [26]:
ranarr

array([16, 49, 28,  9,  0,  7, 33, 20, 47,  7])

In [27]:
ranarr.max()

49

In [28]:
ranarr.argmax()

1

In [29]:
ranarr.min()

0

In [30]:
ranarr.argmin()

4

## Shape

Shape is an attribute that arrays have (not a method):

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
# Vector
arr.shape

(20,)

In [33]:
# Notice the two sets of brackets
arr.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [34]:
arr.reshape(1,20).shape

(1, 20)

In [35]:
arr.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

### dtype

You can also grab the data type of the object in the array:

In [36]:
arr.dtype

dtype('int32')

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [63]:
#Creating sample array
arr = np.arange(0,11)

In [65]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [67]:
#Get a value at an index
arr[5]

5

In [68]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [69]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [85]:
arr[0:5]

array([100, 100, 100, 100, 100])

In [86]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100
#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [87]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [89]:
#Important notes on Slices
slice_of_arr = arr[0:6]
#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [93]:
#Change Slice
slice_of_arr[0:6]=100
#Show Slice again
slice_of_arr

array([100, 100, 100, 100, 100, 100])

Now note the changes also occur in our original array!

In [94]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [76]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [45]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [46]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [47]:
# Format is arr_2d[row][col] or arr_2d[row,col]
# Getting individual element value
arr_2d[1][0]

20

In [48]:
# Getting individual element value
arr_2d[1,0]

20

In [49]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [50]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [51]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [52]:
#Set up matrix
arr2d = np.zeros((10,10))

In [53]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [56]:
arr2d.shape

(10, 10)

In [59]:
#Length of array
arr_length = arr2d.shape[0]

In [60]:
arr_length

10

In [62]:
#Set up array

for i in range(arr_length):
    #print(i)
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [63]:
arr2d[1,1]

1.0

In [64]:
arr2d[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [67]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Comparison operators and Boolean



'=='	equal	

'!='	not_equal

'<'	    less	

'<='	less_equal

'>'     greater

'>='    greater_equal

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [70]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [73]:
bool_arr = arr>4

In [75]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [77]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [78]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr<3

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [82]:
arr<=3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [85]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Check for >=, !=, ==

In [86]:
np.sum(arr>6)

4

In [87]:
np.sum(arr>=6)

5

In [91]:
np.any(arr>=11)

False

In [89]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
np.any(arr>10)

False

In [95]:
np.all(arr<10)

False

# NumPy Concatenation and splitting

In this lecture we will discuss how to concatenate and split arrays

Concatenation or joining of two arrays is done by using certain functions.

In [2]:
import numpy as np

In [97]:
arr_1=([1,2,3])
arr_2=([4,5,6])

In [98]:
arr_2

[4, 5, 6]

In [100]:
np.concatenate([arr_1,arr_2])

array([1, 2, 3, 4, 5, 6])

In [101]:
arr_3=([7,8,9,10,11])

In [102]:
np.concatenate([arr_1,arr_3,arr_2])

array([ 1,  2,  3,  7,  8,  9, 10, 11,  4,  5,  6])

In [103]:
arr_4=([1,2,3],[4,5,6])
arr_5=([7,8,9],[10,11,12])

In [104]:
arr_4

([1, 2, 3], [4, 5, 6])

In [105]:
arr_5

([7, 8, 9], [10, 11, 12])

In [107]:
np.concatenate([arr_4,arr_5])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [108]:
np.concatenate([arr_4,arr_5],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [110]:
arr_1

[1, 2, 3]

In [111]:
arr_4

([1, 2, 3], [4, 5, 6])

In [113]:
np.concatenate([arr_1,arr_4])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [114]:
arr_1

[1, 2, 3]

In [115]:
arr_4

([1, 2, 3], [4, 5, 6])

In [119]:
np.vstack([arr_1,arr_4])


# The np.vstack() function in NumPy is used to vertically stack arrays. 
# It combines arrays by stacking them vertically, which means it adds rows to the arrays being stacked. 
# Here's how you can use np.vstack() with your arr_1 and arr_4:

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [120]:
np.hstack([arr_1,arr_4])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [121]:
arr_6=([100],[200])

In [59]:
arr_6

([100], [200])

In [122]:
arr_4

([1, 2, 3], [4, 5, 6])

In [123]:
np.hstack([arr_4,arr_6])

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200]])

Look for the dimensions before applying np.hstack and np.vstack

# Splitting the arrays

The opposite of concatenation is to split the arrays

In [126]:
arra_1=([1,2,3,4,5,6,7,8])

Array indices 3 and 5 are where split is to be done.

In [131]:
np.split(arra_1,[3,5,7])

# From index 0 to index 3 (exclusive): [1, 2, 3]
# From index 3 to index 5 (exclusive): [4, 5]
# From index 5 to the end: [6, 7, 8]

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8])]

In [137]:
np.split(arra_1,[1,4])[1]

# From index 0 to index 1 (exclusive): [1]
# From index 1 to index 4 (exclusive): [2, 3, 4]
# From index 4 to the end: [5, 6, 7, 8]

array([2, 3, 4])

In [134]:
np.split(arra_1,[4])

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [164]:
grid=np.arange(16)



In [165]:
grid


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [169]:
grid=grid.reshape(4,4)

In [170]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [171]:
np.vsplit(grid,[3])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [172]:
np.hsplit(grid,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [174]:
import numpy as np
arr = np.arange(0,10)

In [175]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [176]:
arr1 = np.arange(0,5)
arr1

array([0, 1, 2, 3, 4])

In [178]:
arr + arr1

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [179]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [180]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [181]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [182]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

C:\Users\krish\AppData\Local\Temp\ipykernel_21392\2878212635.py:3: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [183]:
# Also warning, but not an error instead infinity
1/arr

C:\Users\krish\AppData\Local\Temp\ipykernel_21392\1360216608.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [184]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [190]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [186]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [187]:
np.max(arr) #same as arr.max()

9

In [191]:
np.min(arr) #same as arr.max()

0

In [188]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [189]:
np.log(arr)

C:\Users\krish\AppData\Local\Temp\ipykernel_21392\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# Aggregation : Min, Max, and Everything In Between

* NumPy has fast built-in aggregation functions for working on arrays

In [193]:
import numpy as np
import time

In [211]:
X=np.random.random(50)


We created an array of 50 random numbers and assigned it to X

In [205]:
sum(X)

24.15491332931427

sum() is a function to sum the elements of data type. We can do it using np.sum and observe the result.What's the difference then?

In [206]:
np.sum(X)

24.15491332931427

Let us create a big array of 1000000 elements

In [212]:
X_ = np.random.rand(1000000)

In [216]:
%timeit sum(X_)


53.3 ms ± 921 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [214]:
%timeit np.sum(X_)

454 µs ± 46.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Note : The time taken for both the functions is quite significant.

# Minimum and Maximum

In [ ]:
%timeit min(X_),max(X_)

745 ms ± 116 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit np.min(X_),np.max(X_)

1.91 ms ± 386 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%timeit X_.min(),X_.max()

1.68 ms ± 41.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


np.min(X_) is same as X_.min()

Aggregation on 2-D array

In [ ]:
X = np.random.random((3,4))

In [ ]:
X

array([[0.00299008, 0.70363886, 0.82929294, 0.32279649],
       [0.3763851 , 0.01289159, 0.42135329, 0.7628759 ],
       [0.8365313 , 0.02018789, 0.89167764, 0.90391708]])

In [ ]:
X.sum()

6.084538166887024

Returns the sum of all elements of the array

In [ ]:
X.sum(axis=0)

array([1.21590649, 0.73671835, 2.14232386, 1.98958946])

In [ ]:
X.min(axis=0)

array([0.00299008, 0.01289159, 0.42135329, 0.32279649])

Observe X.max, X.max(axis=1)

In [ ]:
X.max(axis=1)

array([0.82929294, 0.7628759 , 0.90391708])

In [22]:
X = np.random.randint(10 ,size= (2,2))
X

array([[0, 8],
       [2, 7]])

In [ ]:
np.mean(X)

3.75

In [ ]:
np.std(X)

3.344772040064913

In [ ]:
np.var(X)

11.1875

In [ ]:
np.argmin(X)

0

In [ ]:
np.argmax(X)

2

In [ ]:
np.median(X)

3.5

# Combined Indexing

In [79]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [80]:
x[[1, 1, 2], [0, 1, 1]]    #((1,0),(1,1),(2,1))

array([3, 4, 6])

In [81]:
x[1:2]

array([[3, 4]])

In [82]:
x[1:3]

array([[3, 4],
       [5, 6]])

In [ ]:
x[1:2, 1:3]

# x[1:2, 1:3] is a way to pick a subset of this array.
# 1:2 means you want rows from index 1 up to (but not including) index 2. This selects only the second row: [3, 4].
# 1:3 means you want columns from index 1 up to (but not including) index 3. This selects only the second column: [2, 4, 6].

array([[4]])

# Sorting

In [83]:
x= np.array([100,78,56,45,67,90,67])

In [84]:
np.sort(x)

array([ 45,  56,  67,  67,  78,  90, 100])

In [85]:
x=np.array([1,2,3,4,2,7,90,34,4,5])

In [ ]:
np.sort(x)[::-1]

array([90, 34,  7,  5,  4,  4,  3,  2,  2,  1])

In [ ]:
np.sort(x)[::-2]

array([90,  7,  4,  3,  2])

In [ ]:
x

array([ 1,  2,  3,  4,  2,  7, 90, 34,  4,  5])

In [86]:
np.argsort(x)

array([0, 1, 4, 2, 3, 8, 9, 5, 7, 6], dtype=int64)

Creates a copy of the array with its elements rearranged in such a way that the value of the element in k-th position is in the position it would be in a sorted array. All elements smaller than the k-th element are moved before this element and all equal or greater are moved behind it. The ordering of the elements in the two partitions is undefined.

In [ ]:
a = np.array([20,6,12,9,10,3,5,17,2,15])

In [ ]:
np.partition(a,5)

array([ 3,  2,  5,  6,  9, 10, 12, 15, 17, 20])